name: Webhostmost Login and Status Check

on:
  schedule:
    - cron: '0 0 */10 * *'
  workflow_dispatch:

jobs:
  login_and_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install puppeteer cheerio uuid

      - name: Run login and status check script
        id: run_check
        env:
          WEBHOSTMOST_USERNAME: ${{ secrets.WEBHOSTMOST_USERNAME }}
          WEBHOSTMOST_PASSWORD: ${{ secrets.WEBHOSTMOST_PASSWORD }}
        run: node webhostmost_check.js

      - name: Send Telegram Notification
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="${{ steps.run_check.outputs.status }}"
          if [ -n "$MESSAGE" ] && [ -n "${TELEGRAM_BOT_TOKEN}" ] && [ -n "${TELEGRAM_CHAT_ID}" ]; then
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              -d chat_id="${TELEGRAM_CHAT_ID}" \
              -d text="$MESSAGE" \
              -d disable_web_page_preview="true"
          else
            echo "Missing Telegram config or empty message. Skipping notification."
          fi
        continue-on-error: true

      - name: Output Status
        run: echo "${{ steps.run_check.outputs.status }}"
