name: WebhostMost Keep Alive

on:
  schedule:
    - cron: "0 0 * * *" # 每天 00:00 UTC 执行
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    env:
      WEBHOSTMOST_USERNAME: ${{ secrets.WEBHOSTMOST_USERNAME }}
      WEBHOSTMOST_PASSWORD: ${{ secrets.WEBHOSTMOST_PASSWORD }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install puppeteer node-telegram-bot-api

      - name: Run check script
        run: node webhostmost_check.js
