name: Webhostmost Login and Telegram

on:
  schedule:
    - cron: '0 0 */10 * *'  # Runs every 10 days at 00:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  login_and_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Uninstall global Puppeteer (if any)
        run: npm uninstall -g puppeteer

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: |
          npm install puppeteer@latest cheerio
          echo "PUPPETEER_CACHE_PATH="
          rm -rf $(npm config get puppeteer_cache_path)
          echo "Puppeteer version: $(npm list puppeteer)"

      - name: Run login and status check script
        env:
          WEBHOSTMOST_USERNAME: ${{ secrets.WEBHOSTMOST_USERNAME }}
          WEBHOSTMOST_PASSWORD: ${{ secrets.WEBHOSTMOST_PASSWORD }}
        run: node ./webhostmost_check.js

      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          STATUS_MESSAGE=$(cat status.txt)
          if [ -n "${TELEGRAM_BOT_TOKEN}" ] && [ -n "${TELEGRAM_CHAT_ID}" ]; then
            MESSAGE="Webhostmost Status: $STATUS_MESSAGE"
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              -d chat_id="${TELEGRAM_CHAT_ID}" \
              -d text="$MESSAGE" \
              -d disable_web_page_preview="true"
          else
            echo "Telegram bot token or chat ID not set. Skipping Telegram notification."
          fi
